############# APP SECTION #############
app:
  name: server_app.app
  websocket: False

############################################################################################
# Comment out app section above if you want to use web sockets and uncomment below seciont #
#app:
#  name: server_app.app_gevent
#  websocket: True

############# ENDPOINTS SECTION #############

endpoints:
  paths:
    -
  blueprints:
    basic_endpoints:
      path:        endpoints
      name:        basic

############# REPOSITORIES SECTION #############

repos:

  main_repo:
    &main_repo
    name:     Main Repo
    path:     UI\scripts

default_repo:  *main_repo

############# SERVER CONFIG SECTION #############

html_output:   UI

host:
  ip:           127.0.0.1
  port:         5000

server_interface:  epyk_app

