repos:

  main_repo:
    &main_repo
    name:     Main Repo
    path:     UI\scripts

default_repo:  *main_repo

html_output:   UI

host:
  ip:           127.0.0.1
  port:         5000

server_interface:  epyk_app

endpoints:
  path:
    -  endpoints
  blueprints:
    epyk_basic_endpoints:
      name:        basic


